//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rKhachHangChanh : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _machanh;
        public int MaChanh { get { return _machanh; } set { SetPropertyAndValidate(ref _machanh, value); } }
    
        private int _makhachhang;
        public int MaKhachHang { get { return _makhachhang; } set { SetPropertyAndValidate(ref _makhachhang, value); } }
    
        private bool _lamacdinh;
        public bool LaMacDinh { get { return _lamacdinh; } set { SetPropertyAndValidate(ref _lamacdinh, value); } }
    
    
        public virtual rChanh rChanh { get; set; }
        public virtual rKhachHang rKhachHang { get; set; }
    }
}
