//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rLoaiChiPhi : BindableObject
    {
        public rLoaiChiPhi()
        {
            this.tChiPhis = new HashSet<tChiPhi>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private string _tenloaichiphi;
        public string TenLoaiChiPhi { get { return _tenloaichiphi; } set { SetPropertyAndValidate(ref _tenloaichiphi, value); } }
    
    
        public virtual ICollection<tChiPhi> tChiPhis { get; set; }
    }
}
