//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rNhanVien : BindableObject
    {
        public rNhanVien()
        {
            this.tChuyenHangs = new HashSet<tChuyenHang>();
            this.tChiPhis = new HashSet<tChiPhi>();
            this.tNhapHangs = new HashSet<tNhapHang>();
            this.tChuyenKhoes = new HashSet<tChuyenKho>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _maphuongtien;
        public int MaPhuongTien { get { return _maphuongtien; } set { SetPropertyAndValidate(ref _maphuongtien, value); } }
    
        private string _tennhanvien;
        public string TenNhanVien { get { return _tennhanvien; } set { SetPropertyAndValidate(ref _tennhanvien, value); } }
    
    
        public virtual rPhuongTien rPhuongTien { get; set; }
        public virtual ICollection<tChuyenHang> tChuyenHangs { get; set; }
        public virtual ICollection<tChiPhi> tChiPhis { get; set; }
        public virtual ICollection<tNhapHang> tNhapHangs { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes { get; set; }
    }
}
