//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rNuoc : BindableObject
    {
        public rNuoc()
        {
            this.rDiaDiems = new HashSet<rDiaDiem>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private string _tennuoc;
        public string TenNuoc { get { return _tennuoc; } set { SetPropertyAndValidate(ref _tennuoc, value); } }
    
    
        public virtual ICollection<rDiaDiem> rDiaDiems { get; set; }
    }
}
