//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tChuyenHangDonHang : BindableObject
    {
        public tChuyenHangDonHang()
        {
            this.tChiTietChuyenHangDonHangs = new HashSet<tChiTietChuyenHangDonHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _machuyenhang;
        public int MaChuyenHang { get { return _machuyenhang; } set { SetPropertyAndValidate(ref _machuyenhang, value); } }
    
        private int _madonhang;
        public int MaDonHang { get { return _madonhang; } set { SetPropertyAndValidate(ref _madonhang, value); } }
    
    
        public virtual ICollection<tChiTietChuyenHangDonHang> tChiTietChuyenHangDonHangs { get; set; }
        public virtual tChuyenHang tChuyenHang { get; set; }
        public virtual tDonHang tDonHang { get; set; }
    }
}
