//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tChuyenHang : BindableObject
    {
        public tChuyenHang()
        {
            this.tChuyenHangDonHangs = new HashSet<tChuyenHangDonHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _manhanviengiaohang;
        public int MaNhanVienGiaoHang { get { return _manhanviengiaohang; } set { SetPropertyAndValidate(ref _manhanviengiaohang, value); } }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { SetPropertyAndValidate(ref _ngay, value); } }
    
        private Nullable<System.TimeSpan> _gio;
        public Nullable<System.TimeSpan> Gio { get { return _gio; } set { SetPropertyAndValidate(ref _gio, value); } }
    
    
        public virtual ICollection<tChuyenHangDonHang> tChuyenHangDonHangs { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
    }
}
