//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tToaHang : BindableObject
    {
        public tToaHang()
        {
            this.tChiTietToaHangs = new HashSet<tChiTietToaHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { SetPropertyAndValidate(ref _ngay, value); } }
    
        private int _makhachhang;
        public int MaKhachHang { get { return _makhachhang; } set { SetPropertyAndValidate(ref _makhachhang, value); } }
    
    
        public virtual rKhachHang rKhachHang { get; set; }
        public virtual ICollection<tChiTietToaHang> tChiTietToaHangs { get; set; }
    }
}
