//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhDataEntity
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tTonKho : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _makhohang;
        public int MaKhoHang { get { return _makhohang; } set { SetPropertyAndValidate(ref _makhohang, value); } }
    
        private int _mamathang;
        public int MaMatHang { get { return _mamathang; } set { SetPropertyAndValidate(ref _mamathang, value); } }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { SetPropertyAndValidate(ref _ngay, value); } }
    
        private int _soluong;
        public int SoLuong { get { return _soluong; } set { SetPropertyAndValidate(ref _soluong, value); } }
    
        private int _soluongcu;
        public int SoLuongCu { get { return _soluongcu; } set { SetPropertyAndValidate(ref _soluongcu, value); } }
    
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual tMatHang tMatHang { get; set; }
    }
}
