//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rBaiXe : BindableObject
    {
        public rBaiXe()
        {
            this.rChanhs = new HashSet<rChanh>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private string _diadiembaixe;
        public string DiaDiemBaiXe { get { return _diadiembaixe; } set { if(_diadiembaixe == value) return; _diadiembaixe = value; base.RaisePropertyChanged("DiaDiemBaiXe");} }
    
    
        public virtual ICollection<rChanh> rChanhs { get; set; }
    }
}
