//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rCanhBaoTonKho : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _mamathang;
        public int MaMatHang { get { return _mamathang; } set { if(IsValid(value, "MaMatHang") == false || _mamathang == value) return; _mamathang = value; base.RaisePropertyChanged("MaMatHang");} }
    
        private int _makhohang;
        public int MaKhoHang { get { return _makhohang; } set { if(IsValid(value, "MaKhoHang") == false || _makhohang == value) return; _makhohang = value; base.RaisePropertyChanged("MaKhoHang");} }
    
        private int _toncaonhat;
        public int TonCaoNhat { get { return _toncaonhat; } set { if(IsValid(value, "TonCaoNhat") == false || _toncaonhat == value) return; _toncaonhat = value; base.RaisePropertyChanged("TonCaoNhat");} }
    
        private int _tonthapnhat;
        public int TonThapNhat { get { return _tonthapnhat; } set { if(IsValid(value, "TonThapNhat") == false || _tonthapnhat == value) return; _tonthapnhat = value; base.RaisePropertyChanged("TonThapNhat");} }
    
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual tMatHang tMatHang { get; set; }
    }
}
