//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rChanh : BindableObject
    {
        public rChanh()
        {
            this.tDonHangs = new HashSet<tDonHang>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _mabaixe;
        public int MaBaiXe { get { return _mabaixe; } set { if(_mabaixe == value) return; _mabaixe = value; base.RaisePropertyChanged("MaBaiXe");} }
    
        private string _tenchanh;
        public string TenChanh { get { return _tenchanh; } set { if(_tenchanh == value) return; _tenchanh = value; base.RaisePropertyChanged("TenChanh");} }
    
    
        public virtual rBaiXe rBaiXe { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
    }
}
