//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rDiaDiem : BindableObject
    {
        public rDiaDiem()
        {
            this.rKhachHangs = new HashSet<rKhachHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _manuoc;
        public int MaNuoc { get { return _manuoc; } set { if(IsValid(value, "MaNuoc") == false || _manuoc == value) return; _manuoc = value; base.RaisePropertyChanged("MaNuoc");} }
    
        private string _tinh;
        public string Tinh { get { return _tinh; } set { if(IsValid(value, "Tinh") == false || _tinh == value) return; _tinh = value; base.RaisePropertyChanged("Tinh");} }
    
    
        public virtual rNuoc rNuoc { get; set; }
        public virtual ICollection<rKhachHang> rKhachHangs { get; set; }
    }
}
