//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhachHang
    {
        public rKhachHang()
        {
            this.tDonHangs = new HashSet<tDonHang>();
        }
    
        public int Ma { get; set; }
        public int MaDiaDiem { get; set; }
        public string TenKhachHang { get; set; }
    
        public virtual rDiaDiem rDiaDiem { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
    }
}
