//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhachHang : BindableObject
    {
        public rKhachHang()
        {
            this.tDonHangs = new HashSet<tDonHang>();
            this.rKhachHangChanhs = new HashSet<rKhachHangChanh>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _madiadiem;
        public int MaDiaDiem { get { return _madiadiem; } set { if(_madiadiem == value) return; _madiadiem = value; base.RaisePropertyChanged("MaDiaDiem");} }
    
        private string _tenkhachhang;
        public string TenKhachHang { get { return _tenkhachhang; } set { if(_tenkhachhang == value) return; _tenkhachhang = value; base.RaisePropertyChanged("TenKhachHang");} }
    
    
        public virtual rDiaDiem rDiaDiem { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
        public virtual ICollection<rKhachHangChanh> rKhachHangChanhs { get; set; }
    }
}
