//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhachHangChanh : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _machanh;
        public int MaChanh { get { return _machanh; } set { if(IsValid(value, "MaChanh") == false || _machanh == value) return; _machanh = value; base.RaisePropertyChanged("MaChanh");} }
    
        private int _makhachhang;
        public int MaKhachHang { get { return _makhachhang; } set { if(IsValid(value, "MaKhachHang") == false || _makhachhang == value) return; _makhachhang = value; base.RaisePropertyChanged("MaKhachHang");} }
    
        private bool _lamacdinh;
        public bool LaMacDinh { get { return _lamacdinh; } set { if(IsValid(value, "LaMacDinh") == false || _lamacdinh == value) return; _lamacdinh = value; base.RaisePropertyChanged("LaMacDinh");} }
    
    
        public virtual rChanh rChanh { get; set; }
        public virtual rKhachHang rKhachHang { get; set; }
    }
}
