//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rKhoHang : BindableObject
    {
        public rKhoHang()
        {
            this.tDonHangs = new HashSet<tDonHang>();
            this.tNhapMatHangs = new HashSet<tNhapMatHang>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private string _tenkho;
        public string TenKho { get { return _tenkho; } set { if(_tenkho == value) return; _tenkho = value; base.RaisePropertyChanged("TenKho");} }
    
        private bool _trangthai;
        public bool TrangThai { get { return _trangthai; } set { if(_trangthai == value) return; _trangthai = value; base.RaisePropertyChanged("TrangThai");} }
    
    
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
        public virtual ICollection<tNhapMatHang> tNhapMatHangs { get; set; }
    }
}
