//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rKhoHang : BindableObject
    {
        public rKhoHang()
        {
            this.tDonHangs = new HashSet<tDonHang>();
            this.tTonKhoes = new HashSet<tTonKho>();
            this.tNhapHangs = new HashSet<tNhapHang>();
            this.tChuyenKhoes = new HashSet<tChuyenKho>();
            this.tChuyenKhoes1 = new HashSet<tChuyenKho>();
            this.rCanhBaoTonKhoes = new HashSet<rCanhBaoTonKho>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private string _tenkho;
        public string TenKho { get { return _tenkho; } set { SetPropertyAndValidate(ref _tenkho, value); } }
    
        private bool _trangthai;
        public bool TrangThai { get { return _trangthai; } set { SetPropertyAndValidate(ref _trangthai, value); } }
    
    
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
        public virtual ICollection<tTonKho> tTonKhoes { get; set; }
        public virtual ICollection<tNhapHang> tNhapHangs { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes { get; set; }
        public virtual ICollection<tChuyenKho> tChuyenKhoes1 { get; set; }
        public virtual ICollection<rCanhBaoTonKho> rCanhBaoTonKhoes { get; set; }
    }
}
