//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rLoaiChiPhi : BindableObject
    {
        public rLoaiChiPhi()
        {
            this.tChiPhis = new HashSet<tChiPhi>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private string _tenloaichiphi;
        public string TenLoaiChiPhi { get { return _tenloaichiphi; } set { if(IsValid(value, "TenLoaiChiPhi") == false || _tenloaichiphi == value) return; _tenloaichiphi = value; base.RaisePropertyChanged("TenLoaiChiPhi");} }
    
    
        public virtual ICollection<tChiPhi> tChiPhis { get; set; }
    }
}
