//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rNguyenLieu : BindableObject
    {
        public rNguyenLieu()
        {
            this.rMatHangNguyenLieux = new HashSet<rMatHangNguyenLieu>();
            this.tNhapNguyenLieux = new HashSet<tNhapNguyenLieu>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _maloainguyenlieu;
        public int MaLoaiNguyenLieu { get { return _maloainguyenlieu; } set { if(IsValid(value, "MaLoaiNguyenLieu") == false || _maloainguyenlieu == value) return; _maloainguyenlieu = value; base.RaisePropertyChanged("MaLoaiNguyenLieu");} }
    
        private int _duongkinh;
        public int DuongKinh { get { return _duongkinh; } set { if(IsValid(value, "DuongKinh") == false || _duongkinh == value) return; _duongkinh = value; base.RaisePropertyChanged("DuongKinh");} }
    
    
        public virtual rLoaiNguyenLieu rLoaiNguyenLieu { get; set; }
        public virtual ICollection<rMatHangNguyenLieu> rMatHangNguyenLieux { get; set; }
        public virtual ICollection<tNhapNguyenLieu> tNhapNguyenLieux { get; set; }
    }
}
