//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rNhaCungCap : BindableObject
    {
        public rNhaCungCap()
        {
            this.tNhapNguyenLieux = new HashSet<tNhapNguyenLieu>();
            this.tNhapHangs = new HashSet<tNhapHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private string _tennhacungcap;
        public string TenNhaCungCap { get { return _tennhacungcap; } set { SetPropertyAndValidate(ref _tennhacungcap, value); } }
    
    
        public virtual ICollection<tNhapNguyenLieu> tNhapNguyenLieux { get; set; }
        public virtual ICollection<tNhapHang> tNhapHangs { get; set; }
    }
}
