//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rNhanVienGiaoHang
    {
        public rNhanVienGiaoHang()
        {
            this.tChiPhiNhanVienGiaoHangs = new HashSet<tChiPhiNhanVienGiaoHang>();
            this.tChuyenHangs = new HashSet<tChuyenHang>();
        }
    
        public int Ma { get; set; }
        public int MaPhuongTien { get; set; }
        public string TenNhanVien { get; set; }
    
        public virtual rPhuongTien rPhuongTien { get; set; }
        public virtual ICollection<tChiPhiNhanVienGiaoHang> tChiPhiNhanVienGiaoHangs { get; set; }
        public virtual ICollection<tChuyenHang> tChuyenHangs { get; set; }
    }
}
