//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class rNhaCungCap : BindableObject
    {
        public rNhaCungCap()
        {
            this.tNhapNguyenLieux = new HashSet<tNhapNguyenLieu>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private string _tennhacungcap;
        public string TenNhaCungCap { get { return _tennhacungcap; } set { if(_tennhacungcap == value) return; _tennhacungcap = value; base.RaisePropertyChanged("TenNhaCungCap");} }
    
    
        public virtual ICollection<tNhapNguyenLieu> tNhapNguyenLieux { get; set; }
    }
}
