//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class rNuoc : BindableObject
    {
        public rNuoc()
        {
            this.rDiaDiems = new HashSet<rDiaDiem>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private string _tennuoc;
        public string TenNuoc { get { return _tennuoc; } set { if(IsValid(value, "TenNuoc") == false || _tennuoc == value) return; _tennuoc = value; base.RaisePropertyChanged("TenNuoc");} }
    
    
        public virtual ICollection<rDiaDiem> rDiaDiems { get; set; }
    }
}
