//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tChiTietChuyenHangDonHang : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _machuyenhangdonhang;
        public int MaChuyenHangDonHang { get { return _machuyenhangdonhang; } set { SetPropertyAndValidate(ref _machuyenhangdonhang, value); } }
    
        private int _machitietdonhang;
        public int MaChiTietDonHang { get { return _machitietdonhang; } set { SetPropertyAndValidate(ref _machitietdonhang, value); } }
    
        private int _soluong;
        public int SoLuong { get { return _soluong; } set { SetPropertyAndValidate(ref _soluong, value); } }
    
    
        public virtual tChiTietDonHang tChiTietDonHang { get; set; }
        public virtual tChuyenHangDonHang tChuyenHangDonHang { get; set; }
    }
}
