//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tChiTietNhapHang : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _manhaphang;
        public int MaNhapHang { get { return _manhaphang; } set { SetPropertyAndValidate(ref _manhaphang, value); } }
    
        private int _mamathang;
        public int MaMatHang { get { return _mamathang; } set { SetPropertyAndValidate(ref _mamathang, value); } }
    
        private int _soluong;
        public int SoLuong { get { return _soluong; } set { SetPropertyAndValidate(ref _soluong, value); } }
    
    
        public virtual tNhapHang tNhapHang { get; set; }
        public virtual tMatHang tMatHang { get; set; }
    }
}
