//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChiTietChuyenHangDonHang
    {
        public int Ma { get; set; }
        public int MaChuyenHangDonHang { get; set; }
        public int MaMatHang { get; set; }
        public int SoLuong { get; set; }
    
        public virtual tChuyenHangDonHang tChuyenHangDonHang { get; set; }
        public virtual tMatHang tMatHang { get; set; }
    }
}
