//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChuyenHangDonHang : BindableObject
    {
        public tChuyenHangDonHang()
        {
            this.tChiTietChuyenHangDonHangs = new HashSet<tChiTietChuyenHangDonHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _machuyenhang;
        public int MaChuyenHang { get { return _machuyenhang; } set { if(IsValid(value, "MaChuyenHang") == false || _machuyenhang == value) return; _machuyenhang = value; base.RaisePropertyChanged("MaChuyenHang");} }
    
        private int _madonhang;
        public int MaDonHang { get { return _madonhang; } set { if(IsValid(value, "MaDonHang") == false || _madonhang == value) return; _madonhang = value; base.RaisePropertyChanged("MaDonHang");} }
    
    
        public virtual ICollection<tChiTietChuyenHangDonHang> tChiTietChuyenHangDonHangs { get; set; }
        public virtual tChuyenHang tChuyenHang { get; set; }
        public virtual tDonHang tDonHang { get; set; }
    }
}
