//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tChuyenKho : BindableObject
    {
        public tChuyenKho()
        {
            this.tChiTietChuyenKhoes = new HashSet<tChiTietChuyenKho>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _manhanvien;
        public int MaNhanVien { get { return _manhanvien; } set { SetPropertyAndValidate(ref _manhanvien, value); } }
    
        private int _makhohangxuat;
        public int MaKhoHangXuat { get { return _makhohangxuat; } set { SetPropertyAndValidate(ref _makhohangxuat, value); } }
    
        private int _makhohangnhap;
        public int MaKhoHangNhap { get { return _makhohangnhap; } set { SetPropertyAndValidate(ref _makhohangnhap, value); } }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { SetPropertyAndValidate(ref _ngay, value); } }
    
    
        public virtual rKhoHang rKhoHangNhap { get; set; }
        public virtual rKhoHang rKhoHangXuat { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
        public virtual ICollection<tChiTietChuyenKho> tChiTietChuyenKhoes { get; set; }
    }
}
