//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tChuyenHang
    {
        public tChuyenHang()
        {
            this.tDonHangs = new HashSet<tDonHang>();
        }
    
        public int Ma { get; set; }
        public int MaNhanVienGiaoHang { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<System.TimeSpan> Gio { get; set; }
    
        public virtual rNhanVienGiaoHang rNhanVienGiaoHang { get; set; }
        public virtual ICollection<tDonHang> tDonHangs { get; set; }
    }
}
