//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDonHang
    {
        public tDonHang()
        {
            this.tChiTietDonHangs = new HashSet<tChiTietDonHang>();
        }
    
        public int Ma { get; set; }
        public int MaChuyenHang { get; set; }
        public string TenKhachHang { get; set; }
        public Nullable<int> MaBaiXe { get; set; }
        public Nullable<int> MaChanh { get; set; }
    
        public virtual rBaiXe rBaiXe { get; set; }
        public virtual rChanh rChanh { get; set; }
        public virtual ICollection<tChiTietDonHang> tChiTietDonHangs { get; set; }
        public virtual tChuyenHang tChuyenHang { get; set; }
    }
}
