//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tDonHang : BindableObject
    {
        public tDonHang()
        {
            this.tChiTietDonHangs = new HashSet<tChiTietDonHang>();
            this.tChuyenHangDonHangs = new HashSet<tChuyenHangDonHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _makhachhang;
        public int MaKhachHang { get { return _makhachhang; } set { if(IsValid(value, "MaKhachHang") == false || _makhachhang == value) return; _makhachhang = value; base.RaisePropertyChanged("MaKhachHang");} }
    
        private Nullable<int> _machanh;
        public Nullable<int> MaChanh { get { return _machanh; } set { if(IsValid(value, "MaChanh") == false || _machanh == value) return; _machanh = value; base.RaisePropertyChanged("MaChanh");} }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { if(IsValid(value, "Ngay") == false || _ngay == value) return; _ngay = value; base.RaisePropertyChanged("Ngay");} }
    
        private bool _xong;
        public bool Xong { get { return _xong; } set { if(IsValid(value, "Xong") == false || _xong == value) return; _xong = value; base.RaisePropertyChanged("Xong");} }
    
        private int _makhohang;
        public int MaKhoHang { get { return _makhohang; } set { if(IsValid(value, "MaKhoHang") == false || _makhohang == value) return; _makhohang = value; base.RaisePropertyChanged("MaKhoHang");} }
    
    
        public virtual rChanh rChanh { get; set; }
        public virtual rKhachHang rKhachHang { get; set; }
        public virtual ICollection<tChiTietDonHang> tChiTietDonHangs { get; set; }
        public virtual ICollection<tChuyenHangDonHang> tChuyenHangDonHangs { get; set; }
        public virtual rKhoHang rKhoHang { get; set; }
    }
}
