//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class ThamSoNgay : BindableObject
    {
        private string _ten;
        public string Ten { get { return _ten; } set { if(IsValid(value, "Ten") == false || _ten == value) return; _ten = value; base.RaisePropertyChanged("Ten");} }
    
        private System.DateTime _giatri;
        public System.DateTime GiaTri { get { return _giatri; } set { if(IsValid(value, "GiaTri") == false || _giatri == value) return; _giatri = value; base.RaisePropertyChanged("GiaTri");} }
    
    }
}
