//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tMatHang : BindableObject
    {
        public tMatHang()
        {
            this.tChiTietDonHangs = new HashSet<tChiTietDonHang>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _maloai;
        public int MaLoai { get { return _maloai; } set { if(_maloai == value) return; _maloai = value; base.RaisePropertyChanged("MaLoai");} }
    
        private string _tenmathang;
        public string TenMatHang { get { return _tenmathang; } set { if(_tenmathang == value) return; _tenmathang = value; base.RaisePropertyChanged("TenMatHang");} }
    
        private int _soky;
        public int SoKy { get { return _soky; } set { if(_soky == value) return; _soky = value; base.RaisePropertyChanged("SoKy");} }
    
        private int _somet;
        public int SoMet { get { return _somet; } set { if(_somet == value) return; _somet = value; base.RaisePropertyChanged("SoMet");} }
    
    
        public virtual rLoaiHang rLoaiHang { get; set; }
        public virtual ICollection<tChiTietDonHang> tChiTietDonHangs { get; set; }
    }
}
