//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tMatHang : BindableObject
    {
        public tMatHang()
        {
            this.tChiTietDonHangs = new HashSet<tChiTietDonHang>();
            this.rMatHangNguyenLieux = new HashSet<rMatHangNguyenLieu>();
            this.tTonKhoes = new HashSet<tTonKho>();
            this.tChiTietNhapHangs = new HashSet<tChiTietNhapHang>();
            this.tChiTietChuyenKhoes = new HashSet<tChiTietChuyenKho>();
            this.rCanhBaoTonKhoes = new HashSet<rCanhBaoTonKho>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _maloai;
        public int MaLoai { get { return _maloai; } set { SetPropertyAndValidate(ref _maloai, value); } }
    
        private string _tenmathang;
        public string TenMatHang { get { return _tenmathang; } set { SetPropertyAndValidate(ref _tenmathang, value); } }
    
        private int _soky;
        public int SoKy { get { return _soky; } set { SetPropertyAndValidate(ref _soky, value); } }
    
        private int _somet;
        public int SoMet { get { return _somet; } set { SetPropertyAndValidate(ref _somet, value); } }
    
        private string _tenmathangdaydu;
        public string TenMatHangDayDu { get { return _tenmathangdaydu; } set { SetPropertyAndValidate(ref _tenmathangdaydu, value); } }
    
        private string _tenmathangin;
        public string TenMatHangIn { get { return _tenmathangin; } set { SetPropertyAndValidate(ref _tenmathangin, value); } }
    
    
        public virtual rLoaiHang rLoaiHang { get; set; }
        public virtual ICollection<tChiTietDonHang> tChiTietDonHangs { get; set; }
        public virtual ICollection<rMatHangNguyenLieu> rMatHangNguyenLieux { get; set; }
        public virtual ICollection<tTonKho> tTonKhoes { get; set; }
        public virtual ICollection<tChiTietNhapHang> tChiTietNhapHangs { get; set; }
        public virtual ICollection<tChiTietChuyenKho> tChiTietChuyenKhoes { get; set; }
        public virtual ICollection<rCanhBaoTonKho> rCanhBaoTonKhoes { get; set; }
    }
}
