//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNhapHang : BindableObject
    {
        public tNhapHang()
        {
            this.tChiTietNhapHangs = new HashSet<tChiTietNhapHang>();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { if(_ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private int _manhanvien;
        public int MaNhanVien { get { return _manhanvien; } set { if(_manhanvien == value) return; _manhanvien = value; base.RaisePropertyChanged("MaNhanVien");} }
    
        private int _makhohang;
        public int MaKhoHang { get { return _makhohang; } set { if(_makhohang == value) return; _makhohang = value; base.RaisePropertyChanged("MaKhoHang");} }
    
        private int _manhacungcap;
        public int MaNhaCungCap { get { return _manhacungcap; } set { if(_manhacungcap == value) return; _manhacungcap = value; base.RaisePropertyChanged("MaNhaCungCap");} }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { if(_ngay == value) return; _ngay = value; base.RaisePropertyChanged("Ngay");} }
    
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual rNhaCungCap rNhaCungCap { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
        public virtual ICollection<tChiTietNhapHang> tChiTietNhapHangs { get; set; }
    }
}
