//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    using Common;
    
    public partial class tNhapHang : BindableObject
    {
        public tNhapHang()
        {
            this.tChiTietNhapHangs = new HashSet<tChiTietNhapHang>();
            Init();
        }
    
        private int _ma;
        public int Ma { get { return _ma; } set { SetPropertyAndValidate(ref _ma, value); } }
    
        private int _manhanvien;
        public int MaNhanVien { get { return _manhanvien; } set { SetPropertyAndValidate(ref _manhanvien, value); } }
    
        private int _makhohang;
        public int MaKhoHang { get { return _makhohang; } set { SetPropertyAndValidate(ref _makhohang, value); } }
    
        private int _manhacungcap;
        public int MaNhaCungCap { get { return _manhacungcap; } set { SetPropertyAndValidate(ref _manhacungcap, value); } }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { SetPropertyAndValidate(ref _ngay, value); } }
    
    
        public virtual rKhoHang rKhoHang { get; set; }
        public virtual rNhaCungCap rNhaCungCap { get; set; }
        public virtual rNhanVien rNhanVien { get; set; }
        public virtual ICollection<tChiTietNhapHang> tChiTietNhapHangs { get; set; }
    }
}
