//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhuDinhData
{
    using System;
    using System.Collections.Generic;
    
    public partial class tNhapNguyenLieu : BindableObject
    {
        private int _ma;
        public int Ma { get { return _ma; } set { if(IsValid(value, "Ma") == false || _ma == value) return; _ma = value; base.RaisePropertyChanged("Ma");} }
    
        private System.DateTime _ngay;
        public System.DateTime Ngay { get { return _ngay; } set { if(IsValid(value, "Ngay") == false || _ngay == value) return; _ngay = value; base.RaisePropertyChanged("Ngay");} }
    
        private int _manguyenlieu;
        public int MaNguyenLieu { get { return _manguyenlieu; } set { if(IsValid(value, "MaNguyenLieu") == false || _manguyenlieu == value) return; _manguyenlieu = value; base.RaisePropertyChanged("MaNguyenLieu");} }
    
        private int _manhacungcap;
        public int MaNhaCungCap { get { return _manhacungcap; } set { if(IsValid(value, "MaNhaCungCap") == false || _manhacungcap == value) return; _manhacungcap = value; base.RaisePropertyChanged("MaNhaCungCap");} }
    
        private int _soluong;
        public int SoLuong { get { return _soluong; } set { if(IsValid(value, "SoLuong") == false || _soluong == value) return; _soluong = value; base.RaisePropertyChanged("SoLuong");} }
    
    
        public virtual rNguyenLieu rNguyenLieu { get; set; }
        public virtual rNhaCungCap rNhaCungCap { get; set; }
    }
}
